#ifndef WEAPONID_CONST_H
#define WEAPONID_CONST_H
#ifdef _WIN32
#pragma once
#endif

enum WeaponIDPrimaryType : byte
{
	WEAPON_NULL0,

	/*EPIC WEAPON*/
	WEAPON_HALOGUN,
	WEAPON_WONDERCANNONEX,
	WEAPON_WONDERCANNON,
	WEAPON_REVIVEGUN,
	WEAPON_GUNGNIR,

	/*OVERCOMING WEAPON*/
	WEAPON_HUNTBOW,
	WEAPON_SGDRILL,
	WEAPON_CANNON,
	WEAPON_PALADIN,
	WEAPON_BUFFM4A1,
	WEAPON_CHAINSAW,
	WEAPON_GATLING,
	WEAPON_GATLINGEX,
	WEAPON_BUFFAUG,

	/*RARE WEAPON*/
	WEAPON_STARCHASERAR,
	WEAPON_BALROG3,
	WEAPON_BALROG5,
	WEAPON_BALROG7,
	WEAPON_BALROG11,
	WEAPON_ETHEREAL,
	WEAPON_STUNRIFLE,
	WEAPON_BOW,
	WEAPON_PLASMAGUN,
	WEAPON_POISONGUN,

	WEAPON_COILGUN,
	WEAPON_BROAD,
	WEAPON_SVDEX,
	WEAPON_TBARREL,

	WEAPON_KRISS,
	WEAPON_SCAR,
	WEAPON_THOMPSON,
	WEAPON_TAR21,
	WEAPON_MP7A1,
	WEAPON_M14EBR,
	WEAPON_GUITAR,
	WEAPON_JANUS7XMAS,
	WEAPON_K1A,
	WEAPON_AS50,
	WEAPON_WA2000,
	WEAPON_M95XMAS,
	WEAPON_M95,
	WEAPON_M134EX,
	WEAPON_M134HERO,
	WEAPON_M134XMAS,
	WEAPON_M1887,
	WEAPON_SCARH,
	WEAPON_SCARL,
	WEAPON_SPAS12EX,
	WEAPON_STG44,
	WEAPON_VIOLINGUN,
	WEAPON_HK23,
	WEAPON_K3,
	WEAPON_M60E4,
	WEAPON_MP5TIGER,
	WEAPON_PKM,

	/*CLASSIC WEAPON*/
	WEAPON_AK47DRAGON,
	WEAPON_M4A1DRAGON,
	WEAPON_TMPDRAGON,
	WEAPON_P90LAPIN,
	WEAPON_MG3,
	WEAPON_XM8,
	WEAPON_M2,
	WEAPON_AK47,
	WEAPON_AUG,
	WEAPON_AWP,
	WEAPON_FAMAS,
	WEAPON_G3SG1,
	WEAPON_GALIL,
	WEAPON_M3,
	WEAPON_M4A1,
	WEAPON_M249,
	WEAPON_MAC10,
	WEAPON_MP5,
	WEAPON_P90,
	WEAPON_SCOUT,
	WEAPON_SG550,
	WEAPON_SG552,
	WEAPON_TMP,
	WEAPON_UMP45,
	WEAPON_XM1014,
};

enum WeaponIDSecondaryType : byte
{
	WEAPON_NULL1,

	/*EPIC PISTOL*/
	WEAPON_VOIDPISTOL,
	WEAPON_VOIDPISTOLEX,

	/*OVERCOMING PISTOL*/
	WEAPON_DESPERADO,
	WEAPON_GUNAKATA,

	/*RARE PISTOL*/
	WEAPON_BALROG1,
	WEAPON_DEAGLED,
	WEAPON_INFINITY,
	WEAPON_INFINITYEX1,
	WEAPON_INFINITYEX2,
	WEAPON_INFINITYSB,
	WEAPON_INFINITYSR,
	WEAPON_INFINITYSS,

	/*CLASSIC PISTOL*/
	WEAPON_DEAGLE,
	WEAPON_ELITE,
	WEAPON_FIVESEVEN,
	WEAPON_GLOCK18,
	WEAPON_USP,
};

enum WeaponIDMeleeType : byte
{
	WEAPON_NULL2,

	/*EPIC KNIFE*/
	WEAPON_TWINAXESEX,
	WEAPON_TWINAXES,

	/*OVERCOMING KNIFE*/
	WEAPON_DUALSWORD,
	WEAPON_STORMGIANT,

	/*RARE KNIFE*/
	WEAPON_BALROG9,
	WEAPON_CLAWHAMMER,
	WEAPON_DRAGONCLAW,
	WEAPON_DUALKATANA,
	WEAPON_NATAKNIFED,
	WEAPON_SERPENTBLADE,
	WEAPON_THANATOS9,
	WEAPON_DRAGONSWORD,
	WEAPON_KATANA,
	WEAPON_SKULLAXE,

	/*CLASSIC KNIFE*/
	WEAPON_KNIFE,

};

enum WeaponIDGrenadeType : byte
{
	WEAPON_NULL3,

	/*EPIC GRENADE*/
	
	/*OVERCOMING GRENADE*/
	WEAPON_SBMINE,

	/*RARE GRENADE*/

	/*CLASSIC GRENADE*/
	WEAPON_HEGRENADE,
	WEAPON_FLASHBANG,
	WEAPON_SMOKEGRENADE,
};

enum WeaponIDZombieType : byte
{
	WEAPON_NULL4,
};

enum WeaponIDItemsType : byte
{
	WEAPON_NULL5,

	/*EPIC ITEMS*/

	/*OVERCOMING ITEMS*/

	/*RARE ITEMS*/

	/*CLASSIC ITEMS*/
};

#endif