
#ifndef ZB2_CONST_H
#define ZB2_CONST_H
#ifdef _WIN32
#pragma once
#endif

enum ZB2MessageType : byte
{
	ZB2_MESSAGE_HEALTH_RECOVERY,
	ZB2_MESSAGE_SKILL_INIT,
	ZB2_MESSAGE_SKILL_ACTIVATE,
	ZB2_MESSAGE_WINHUDHM,
	ZB2_MESSAGE_WINHUDZB,
	ZB2_TEXT_STRING,
	SET_CLASS_MILITIA,
	ORIG_WINCT,
	ORIG_WINT,
	ZOMBIE_INFECTION,
	MAKE_ZOMBIES,
	ZB3_MESSAGE_USED_STATUS,
	ZB2_MESSAGE_ALARM,
	ZB2_RESPZOZOMBIE,
	WPN_ARBALEST2,
	ZB3_GETHERO,
	ZB5_GETHERO,
};

enum ZombieSkillSlot : byte
{
	SKILL_SLOT_CLASS,
	SKILL_SLOT_1,
	SKILL_SLOT_2,
	SKILL_SLOT_3,
	SKILL_SLOT_4,
};

enum ZombieClassType : byte
{
	ZOMBIE_CLASS_HUMAN,
	ZOMBIE_CLASS_TANK,
	ZOMBIE_CLASS_SPEED,
	ZOMBIE_CLASS_HEAVY,
	ZOMBIE_CLASS_PC,
	ZOMBIE_CLASS_HEAL,
	ZOMBIE_CLASS_DEIMOS,
	ZOMBIE_CLASS_DEIMOS2,
	ZOMBIE_CLASS_BANCHEE,
	ZOMBIE_CLASS_STAMPER,

	ZOMBIE_CLASS_MEATWALL,
	ZOMBIE_CLASS_DEATHKNIGHT,
	ZOMBIE_CLASS_SPIDER,

	ZOMBIE_CLASS_AKSHA,
	ZOMBIE_CLASS_BOOMER,
	ZOMBIE_CLASS_BOOSTER,
	ZOMBIE_CLASS_CHINA,
	ZOMBIE_CLASS_FLY,
	ZOMBIE_CLASS_RESIDENT,

	MAX_ZOMBIE_CLASS
};

enum ZombieSkillType : byte
{
	ZOMBIE_SKILL_EMPTY,
	ZOMBIE_SKILL_SPRINT,
	ZOMBIE_SKILL_HEADSHOT,
	ZOMBIE_SKILL_KNIFE2X,
	ZOMBIE_SKILL_CRAZY,
	ZOMBIE_SKILL_HIDE,
	ZOMBIE_SKILL_TRAP,
	ZOMBIE_SKILL_SMOKE,
	ZOMBIE_SKILL_HEAL,
	ZOMBIE_SKILL_SHOCK,
	ZOMBIE_SKILL_CRAZY2,
	ZOMBIE_SKILL_RATS,
	ZOMBIE_SKILL_STAMP,

	ZOMBIE_SKILL_MW,
	ZOMBIE_SKILL_MW2,

	ZOMBIE_SKILL_DK,
	ZOMBIE_SKILL_DK2,

	ZOMBIE_SKILL_SPIDER,
	ZOMBIE_SKILL_SPIDER2,

	ZOMBIE_SKILL_AKSHA,
	ZOMBIE_SKILL_AKSHA2,
	ZOMBIE_SKILL_AKSHA3,

	ZOMBIE_SKILL_BOOMER,
	ZOMBIE_SKILL_BOOMER2,

	ZOMBIE_SKILL_BOOSTER,
	ZOMBIE_SKILL_BOOSTER2,

	ZOMBIE_SKILL_CHINA,
	ZOMBIE_SKILL_CHINA2,

	ZOMBIE_SKILL_FLYING,
	ZOMBIE_SKILL_FLYING2,
	ZOMBIE_SKILL_FLYING3,

	ZOMBIE_SKILL_RESIDENT,
	ZOMBIE_SKILL_RESIDENT2,

	MAX_ZOMBIE_SKILL
};

enum ZombieSkillStatus : byte
{
	SKILL_STATUS_READY,
	SKILL_STATUS_USING,
	SKILL_STATUS_FREEZING,
	SKILL_STATUS_USED
};

#endif